# Generated by Django 3.0.4 on 2020-11-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20201106_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='average_rating',
            field=models.IntegerField(default=0),
        ),
    ]
