# Generated by Django 3.1.2 on 2020-11-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ratings_sum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='reviews_count',
            field=models.IntegerField(default=0),
        ),
    ]
